Revert "Remove `HOMEBREW_NO_AUTO_UPDATE` setting for MacOS builds"
This reverts commit d9a36fc6d4d6558b37717ebc821efc362dcc18a3.

Revert the change from PR #2199. This was a guessed attempt at solving an error without a real understanding of the underlying problem. The error message that lead to the change was:
----
Error: undefined method '[]' for nil
/opt/homebrew/Library/Homebrew/utils/bottles.rb:127:in 'Utils::Bottles.load_tab'
/opt/homebrew/Library/Homebrew/formula_installer.rb:1511:in 'FormulaInstaller#pour'
/opt/homebrew/Library/Homebrew/formula_installer.rb:593:in 'FormulaInstaller#install'
/opt/homebrew/Library/Homebrew/formula_installer.rb:904:in 'FormulaInstaller#install_dependency'
/opt/homebrew/Library/Homebrew/formula_installer.rb:816:in 'block in FormulaInstaller#install_dependencies'
/opt/homebrew/Library/Homebrew/formula_installer.rb:816:in 'Array#each'
/opt/homebrew/Library/Homebrew/formula_installer.rb:816:in 'FormulaInstaller#install_dependencies'
/opt/homebrew/Library/Homebrew/formula_installer.rb:569:in 'FormulaInstaller#install'
/opt/homebrew/Library/Homebrew/install.rb:493:in 'Homebrew::Install.install_formula'
/opt/homebrew/Library/Homebrew/install.rb:420:in 'block in Homebrew::Install.install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:417:in 'Array#each'
/opt/homebrew/Library/Homebrew/install.rb:417:in 'Homebrew::Install.install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:396:in 'Homebrew::Cmd::InstallCmd#run'
/opt/homebrew/Library/Homebrew/brew.rb:101:in '<main>'
You have disabled automatic updates and have not updated today.
Do not report this issue until you've run `brew update` and tried again.
----

After that change, things worked for awhile, and then with a possible update to `brew` or associated Formulas, the error changed to:
----
==> An exception occurred within a child process:
  FormulaUnreadableError: glib: undefined method 'post_install_steps' for class Formulary::FormulaNamespace12065a9a0541c74931a3ef30da099ea0d714a26e58fa45746c9a93a933454385::Glib

/opt/homebrew/opt/glib/.brew/glib.rb:124:in '<class:Glib>'
/opt/homebrew/opt/glib/.brew/glib.rb:1:in 'block in Formulary.load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:145:in 'Module#module_eval'
/opt/homebrew/Library/Homebrew/formulary.rb:145:in 'block in Formulary.load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:157:in 'Formulary.load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:205:in 'Formulary.load_formula_from_path'
/opt/homebrew/Library/Homebrew/formulary.rb:486:in 'Formulary::FormulaLoader#load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:476:in 'Formulary::FormulaLoader#klass'
/opt/homebrew/Library/Homebrew/formulary.rb:470:in 'Formulary::FormulaLoader#get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:994:in 'Formulary.factory'
/opt/homebrew/Library/Homebrew/formulary.rb:379:in 'Formulary.resolve'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:463:in 'Homebrew::CLI::NamedArgs#resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:345:in 'block in Homebrew::CLI::NamedArgs#load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:470:in 'Homebrew.with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:336:in 'Homebrew::CLI::NamedArgs#load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:85:in 'block in Homebrew::CLI::NamedArgs#to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:84:in 'Array#each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:84:in 'Enumerable#flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:84:in 'Homebrew::CLI::NamedArgs#to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:167:in 'Homebrew::CLI::NamedArgs#to_resolved_formulae'
/opt/homebrew/Library/Homebrew/postinstall.rb:28:in '<main>'
----

The two errors appear to indicate a mismatch between Homebrew and the Glib Formula.