Move `#include` outside of unnamed namespace
Names defined in the headers would be placed in the unnamed namespace rather than global scope.

----

On `ARM64` with MSVC the nested `#include` emits the errors:
> error C2664: 'unsigned int `anonymous-namespace'::_InterlockedIncrement(volatile unsigned int *)': cannot convert argument 1 from 'volatile long *' to 'volatile unsigned int *'
> error C2665: '`anonymous-namespace'::_InterlockedIncrement': no overloaded function could convert all the argument types

----

Added unnamed `namespace` in PR #1165, commit: 3a07a4295f7824080e60a97c78cec09515b67341

Added `#include` to existing `#if defined(_WIN32)` block in PR #1305, commit 7c5afafca04132c5462df71699f1ab41fb44ec13